pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                echo "Repository checked out successfully."
            }
        }

        stage('Verify Project Structure') {
            steps {
                dir('DevOps-Project-38/FullStack-Blogging-App') {
                    echo "Current Directory:"
                    bat 'cd'
                    bat 'dir'
                }
            }
        }
    }
}