pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                echo "Repository checked out successfully."
            }
        }

        stage('Build & Test') {
    steps {
        dir('DevOps-Project-38/FullStack-Blogging-App') {
            bat 'mvn clean package'
        }
    }
}
stage('Publish Test Results') {
    steps {
        junit 'DevOps-Project-38/FullStack-Blogging-App/target/surefire-reports/*.xml'
    }
}

        stage('Archive Artifact') {
             steps {
                archiveArtifacts artifacts: 'DevOps-Project-38/FullStack-Blogging-App/target/*.jar', fingerprint: true
    }
}
    }
}