pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                echo "Repository checked out successfully."
            }
        }

        stage('Build') {
            steps {
                dir('DevOps-Project-38/FullStack-Blogging-App') {
                    bat 'mvn clean test'
                }
            }
        }

        stage('Archive Artifact') {
             steps {
                archiveArtifacts artifacts: 'DevOps-Project-38/FullStack-Blogging-App/target/*.jar', fingerprint: true
    }
}
    }
}